version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master

init:
- git config --global core.autocrlf true

before_build:
- dotnet --info
- choco install xunit opencover.portable codecov
- dotnet restore

build:
  project: AddLicenseHeader.sln
  verbosity: minimal

build_script:
- dotnet build

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[AddLicenseHeader*]* -[AddLicenseHeader.Tests*]*" -output:".\AddLicenseHeader_coverage.xml" -oldstyle
- codecov -f "AddLicenseHeader_coverage.xml" -t %CODECOV_TOKEN%

deploy: off
